# Generated by Django 4.0.6 on 2023-01-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPrefrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprefrences',
            options={'verbose_name_plural': 'user Prefrences'},
        ),
    ]
